# Generated by Django 5.0.7 on 2024-07-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0002_uploadedfile_delete_pdffile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadedFile',
            new_name='UploadedPDF',
        ),
    ]
